### ISSUE TITLE
[vite-plugin-vercel] Missing semicolon. (2:11) when enabling this plugin

### ISSUE THREAD

**Issue by CryptoGraffe** [magne4000/vite-plugin-vercel#38]
I've got an app that we are porting to vite. We've got everything working w/o this plugin except our Vercel Serverless functions throw an error when they run in vercel. We get an error about ESM imports from JS file 

```
'ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/var/task/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.```
```

So in looking for help, I came across this plugin which seems to be the thing to help us out - maybe that error is caused from the double compilation situation? 

However, when we enable this plugin we get warnings about import.meta.env not being available to one of our files, and then we get a build failed with this Missing semicolon error, which I have no idea where to look. 

Here is our build output and vite config: 

```

❯ pnpm build

 coordinape-app@0.2.0 build /Users/xyz/dev/coordinape
 tsc && vite build -v

vite v5.0.11 building for production...
✓ 5848 modules transformed.
computing gzip size (9)...
  .vercel/output/functions/api/log.func/index.js  1.1mb ⚠️

⚡ Done in 51ms
dist/index.html                          1.35 kB │ gzip:     0.65 kB
dist/assets/guild-logo-k5GnF_6g.svg     25.75 kB │ gzip:     0.90 kB
dist/assets/index-K6GS1Iq2.css          44.25 kB │ gzip:     7.66 kB
dist/assets/tslib.es6-r0x8Em0Q.js        6.86 kB │ gzip:     2.86 kB
dist/assets/index-cN0BjkqN.js           13.63 kB │ gzip:     5.16 kB
dist/assets/index-kYqkmbI8.js          138.75 kB │ gzip:    43.94 kB
dist/assets/index-XTwhtJOs.js          192.36 kB │ gzip:    63.59 kB
dist/assets/index-2a2mA5ZM.js          299.90 kB │ gzip:    79.17 kB
dist/assets/index.es-ZWlreO9o.js       320.05 kB │ gzip:    97.07 kB
dist/assets/index-N4cogWOD.js        5,002.91 kB │ gzip: 1,510.22 kB

(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
▲ [WARNING] "import.meta" is not available with the "cjs" output format and will be empty [empty-import-meta]

    src/env.ts:3:7:
      3 │   if (!import.meta.env) return 'import.meta.env is undefined' as T;
        ╵        ~~~~~~~~~~~

  You need to set the output format to "esm" for "import.meta" to work correctly.

▲ [WARNING] "import.meta" is not available with the "cjs" output format and will be empty [empty-import-meta]

    src/env.ts:4:12:
      4 │   const v = import.meta.env[key];
        ╵             ~~~~~~~~~~~

  You need to set the output format to "esm" for "import.meta" to work correctly.

2 warnings
▲ [WARNING] "import.meta" is not available with the "cjs" output format and will be empty [empty-import-meta]

    src/env.ts:3:7:
      3 │   if (!import.meta.env) return 'import.meta.env is undefined' as T;
        ╵        ~~~~~~~~~~~

  You need to set the output format to "esm" for "import.meta" to work correctly.

▲ [WARNING] "import.meta" is not available with the "cjs" output format and will be empty [empty-import-meta]

    src/env.ts:4:12:
      4 │   const v = import.meta.env[key];
        ╵             ~~~~~~~~~~~

  You need to set the output format to "esm" for "import.meta" to work correctly.

2 warnings

  .vercel/output/functions/api/login.func/index.js  2.1mb ⚠️

⚡ Done in 128ms

  .vercel/output/functions/api/time.func/index.js  964.4kb

⚡ Done in 51ms
[vite-plugin-vercel] Missing semicolon. (2:11)
✓ built in 10.72s
error during build:
SyntaxError: Missing semicolon. (2:11)
    at constructor (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:356:19)
    at V8IntrinsicMixin.raise (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:3223:19)
    at V8IntrinsicMixin.semicolon (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:3580:10)
    at V8IntrinsicMixin.parseExpressionStatement (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:13158:10)
    at V8IntrinsicMixin.parseExpressionStatement (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:9441:26)
    at V8IntrinsicMixin.parseStatementContent (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:12741:19)
    at V8IntrinsicMixin.parseStatementContent (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:9340:18)
    at V8IntrinsicMixin.parseStatementLike (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:12588:17)
    at V8IntrinsicMixin.parseStatementListItem (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:12568:17)
    at V8IntrinsicMixin.parseBlockOrModuleBlockBody (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:13189:61)
    at V8IntrinsicMixin.parseBlockBody (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:13182:10)
    at V8IntrinsicMixin.parseBlock (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:13170:10)
    at V8IntrinsicMixin.parseStatementContent (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:12690:21)
    at V8IntrinsicMixin.parseStatementContent (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:9340:18)
    at V8IntrinsicMixin.parseStatementLike (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:12588:17)
    at V8IntrinsicMixin.parseModuleItem (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:12565:17)
    at V8IntrinsicMixin.parseBlockOrModuleBlockBody (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:13189:36)
    at V8IntrinsicMixin.parseBlockBody (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:13182:10)
    at V8IntrinsicMixin.parseProgram (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:12464:10)
    at V8IntrinsicMixin.parseTopLevel (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:12454:25)
    at V8IntrinsicMixin.parse (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:14376:10)
    at V8IntrinsicMixin.parse (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:9982:18)
    at Module.parse (/Users/xyz/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:14417:38)
    at Object.parse (file:///Users/xyz/dev/coordinape/node_modules/.pnpm/magicast@0.3.2/node_modules/magicast/dist/index.mjs:7819:26)
    at parse (file:///Users/xyz/dev/coordinape/node_modules/.pnpm/magicast@0.3.2/node_modules/magicast/dist/index.mjs:4590:30)
    at parseModule (file:///Users/xyz/dev/coordinape/node_modules/.pnpm/magicast@0.3.2/node_modules/magicast/dist/index.mjs:8745:16)
    at loadFile (file:///Users/xyz/dev/coordinape/node_modules/.pnpm/magicast@0.3.2/node_modules/magicast/dist/index.mjs:8782:10)
    at async removeDefaultExport (file:///Users/xyz/dev/coordinape/node_modules/.pnpm/vite-plugin-vercel@2.0.0_vite@5.0.11/node_modules/vite-plugin-vercel/dist/index.js:432:15)
    at async extractExports (file:///Users/xyz/dev/coordinape/node_modules/.pnpm/vite-plugin-vercel@2.0.0_vite@5.0.11/node_modules/vite-plugin-vercel/dist/index.js:441:20)
    at async buildEndpoints (file:///Users/xyz/dev/coordinape/node_modules/.pnpm/vite-plugin-vercel@2.0.0_vite@5.0.11/node_modules/vite-plugin-vercel/dist/index.js:466:23)
    at async Object.writeBundle (file:///Users/xyz/dev/coordinape/node_modules/.pnpm/vite-plugin-vercel@2.0.0_vite@5.0.11/node_modules/vite-plugin-vercel/dist/index.js:650:42)
    at async Promise.all (index 0)
    at async PluginDriver.hookParallel (file:///Users/xyz/dev/coordinape/node_modules/.pnpm/rollup@4.9.5/node_modules/rollup/dist/es/shared/node-entry.js:18598:9)
    at async file:///Users/xyz/dev/coordinape/node_modules/.pnpm/rollup@4.9.5/node_modules/rollup/dist/es/shared/node-entry.js:19590:13
    at async catchUnfinishedHookActions (file:///Users/xyz/dev/coordinape/node_modules/.pnpm/rollup@4.9.5/node_modules/rollup/dist/es/shared/node-entry.js:19014:16)
    at async build (file:///Users/xyz/dev/coordinape/node_modules/.pnpm/vite@5.0.11_@types+node@12.20.1/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:67178:22)
    at async CAC.<anonymous> (file:///Users/xyz/dev/coordinape/node_modules/.pnpm/vite@5.0.11_@types+node@12.20.1/node_modules/vite/dist/node/cli.js:845:9)
 ELIFECYCLE  Command failed with exit code 1.

```

Here is my vite.config.ts:

```
import reactRefresh from '@vitejs/plugin-react';
import { defineConfig } from 'vite';
// import EnvironmentPlugin from 'vite-plugin-environment';
import { nodePolyfills } from 'vite-plugin-node-polyfills';
import svgrPlugin from 'vite-plugin-svgr';
import vercel from 'vite-plugin-vercel';
import tsconfigPaths from 'vite-tsconfig-paths';

// https://vitejs.dev/config/
export default defineConfig({
  // This changes the out put dir from dist to build
  // comment this out if that isn't relevant for your project
  appType: 'spa',
  build: {
    outDir: 'dist',
  },
  define: {
    'process.env': {},
    global: {
      window: {
        origin: 'http://localhost:3000',
      },
    },
  },
  plugins: [
    // EnvironmentPlugin('all'),
    nodePolyfills(),
    tsconfigPaths(),
    reactRefresh(),
    svgrPlugin({
      svgrOptions: {
        icon: true,
      },
    }),
    vercel(),
  ],
  test: {
    environment: 'happy-dom',
    include: ['**/*.test.tsx', '**/*.test.ts'],
    globals: true,
    maxConcurrency: 1,
    fileParallelism: false,
    setupFiles: ['./src/setupTests.ts'],
  },
});
```

**Comment by magne4000** [comment]
@CryptoGraffe Thank you for posting a detailed report!

First, regarding the crash, I published `vite-plugin-vercel@2.0.1` that should warn instead of crashing during this process.
In the phase in which it's currently crashing, all endpoints are parsed to check for [specific exported configs](https://github.com/magne4000/vite-plugin-vercel?tab=readme-ov-file#configure-endpoints).
The warning will now contain the path of the file that we could not parse. If possible, once you updated, could you deploy again, check the warning to know which file is incriminated, and post it here?

Regarding `import.meta` warning, it comes from the fact that this plugin bundles your code to CJS with esbuild, and [esbuild does not polyfill](https://github.com/evanw/esbuild/issues/2182) anything usually.
I would suggest to write a helper to check if your env are available in `import.meta` or `process` for a quick workaround. If this works, I will write a small esbuild plugin that transforms `import.meta.env` into `process.env` when outputing CJS.
A real fix would be to output ESM if your are using ESM, but that's a whole task on itself, and I'm still not sure it 100% works on Vercel's side (I need to check what vercel cli does now).
