### ISSUE TITLE
vercel edge functions failing with: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by CryptoGraffe** [magne4000/vite-plugin-vercel#47]
I have gotten my serverless functions working, but now I'm having trouble getting a vercel edge function w/ Satori working. It's an OG Image generator. Here is the error I get when I curl the function:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (node:internal/validators:162:11)
    at join (node:path:1175:7)
    at Object.<anonymous> (/var/task/index.js:77:32029)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at exports.b (/opt/node-bridge/chunk-WW5CSV6R.js:1:1209)
    at /opt/node-bridge/bridge-server-D2QTJ22O.js:1:1443
    at Function.we (/opt/node-bridge/bridge-server-D2QTJ22O.js:1:1809) {
  code: 'ERR_INVALID_ARG_TYPE'
}
INIT_REPORT Init Duration: 560.10 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
Error: Runtime exited without providing a reason
Runtime.ExitError
```

**Comment by CryptoGraffe** [comment]
this is the routing:
```
{
      "source": "/api/og/profileimage/:address",
      "destination": "/api/og/profileimage/[address]?address=:address"
    },
    ```

And this is the code: https://github.com/coordinape/coordinape/blob/vite-colinks/_api/og/profileimage/%5Baddress%5D.tsx

**Comment by CryptoGraffe** [comment]
I figured this out after reading the docs... 

Vercel uses this:

```
export const config = {
  runtime: 'edge',
};
```

whereas this plugin requires:
```
export const edge = true;
```

setting it the latter way worked!

**Comment by magne4000** [comment]
Closing the issue then :)
