### ISSUE TITLE
Can't get @vercel/og working on vercel

### ISSUE THREAD

**Issue by CryptoGraffe** [magne4000/vite-plugin-vercel#56]
I have a node runtime serverless function. If I import @vercel/og and instantiate an ImageResponse, I get this error on vercel:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (node:internal/validators:162:11)
    at join (node:path:1175:7)
    at Object.<anonymous> (/var/task/index.js:157:32390)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at exports.b (/opt/node-bridge/chunk-5UAC7W5H.js:1:1142)
    at /opt/node-bridge/bridge-server-BGIDXK2J.js:1:1443
    at Function.Re (/opt/node-bridge/bridge-server-BGIDXK2J.js:1:1809) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Child exited with error exit status 1INIT_REPORT Init Duration: 474.91 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (node:internal/validators:162:11)
    at join (node:path:1175:7)
    at Object.<anonymous> (/var/task/index.js:157:32390)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at exports.b (/opt/node-bridge/chunk-5UAC7W5H.js:1:1142)
    at /opt/node-bridge/bridge-server-BGIDXK2J.js:1:1443
    at Function.Re (/opt/node-bridge/bridge-server-BGIDXK2J.js:1:1809) {
  code: 'ERR_INVALID_ARG_TYPE'
}
INIT_REPORT Init Duration: 611.82 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
Error: Runtime exited without providing a reason
Runtime.ExitError
```

This works fine in my local express server. It works fine if I do react/jsx but don't use ImageResponse. I have a support ticket open w/ Vercel but they aren't helpful yet. 

Any ideas?

```
❯ curl https://coordinape-git-betterog-coordinape.vercel.app/api/example/works
hi
%

❯ curl https://coordinape-git-betterog-coordinape.vercel.app/api/example/broken
A server error has occurred

FUNCTION_INVOCATION_FAILED
```

See simple code here:

https://github.com/coordinape/coordinape/blob/betterOG/_api/example/works.tsx
https://github.com/coordinape/coordinape/blob/betterOG/_api/example/broken.tsx

**Comment by magne4000** [comment]
Do you also have the error with the edge endpoint https://github.com/coordinape/coordinape/blob/betterOG/_api/example/edge.tsx ?

And if you try [the exact same example as the one in the demo](https://github.com/magne4000/vite-plugin-vercel/blob/main/examples/demo/endpoints/og.tsx), do you also have an error ?

**Comment by CryptoGraffe** [comment]
Edge works fine. The problem is that vercel/og is supposed to work in the
node runtime as well, and we need node runtime to do things like get our
data using graphql client.

**Comment by magne4000** [comment]
I published a new major version, `vite-plugin-vercel@5`, that should fix this issue.

`@vercel/og` support in Node seems to be quite recent, even the official examples only mention Edge endpoint.

@CryptoGraffe [You will have to adapt your handler in order to be able to use `ImageResponse` inde node](https://github.com/magne4000/vite-plugin-vercel/blob/main/examples/demo/endpoints/og-node.tsx).

BREAKING CHANGES:
- Node builds (as opposed to Edge builds) now target ESM (previously it was CJS). This shouldn't cause much issues on most projects, but could on some that uses somewhat broken CJS dependencies

**Comment by CryptoGraffe** [comment]
Now I get this error:

```
Error: ENOENT: no such file or directory, open '/var/task/noto-sans-v27-latin-regular.ttf'
    at Object.openSync (node:fs:581:18)
    at Object.readFileSync (node:fs:457:35)
    at file:///var/task/index.mjs:78396:19
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:431:15)
    at async c (/opt/node-bridge/bridge-server-BGIDXK2J.js:2:3579) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/task/noto-sans-v27-latin-regular.ttf'
}
```

Trying now with our simplified project.

**Comment by CryptoGraffe** [comment]
This was because we were using ReactServerDom w/ ImageResponse to generate a base64 encoded data string. We used your ReadableStream example and everything is working now. 

Thanks again for being so responsive.

**Comment by CryptoGraffe** [comment]
Ok this works great - EXCEPT - it seems to be breaking our cypress tests in CI. What a game of whack-a-mole!

```
Error: ENOENT: no such file or directory, open '/home/circleci/project/.vercel/output/functions/api/time.func/.vc-config.json'
    at Object.wrapChildPromise (/home/circleci/.cache/Cypress/13.6.2/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:58:23)
    at Object.wrap (/home/circleci/.cache/Cypress/13.6.2/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/preprocessor.js:47:8)
    at RunPlugins.execute (/home/circleci/.cache/Cypress/13.6.2/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:157:29)
    at EventEmitter.<anonymous> (/home/circleci/.cache/Cypress/13.6.2/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:56:12)
    at EventEmitter.emit (node:events:518:28)
```

**Comment by CryptoGraffe** [comment]
![image](https://github.com/magne4000/vite-plugin-vercel/assets/95149165/fc541673-b443-42a9-9992-74108eba3fe1)

**Comment by CryptoGraffe** [comment]
Also getting this error on our simpler non-image functions:

It happens with path and url 

```
SyntaxError: Identifier 'url' has already been declared
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:167:18)
    at callTranslator (node:internal/modules/esm/loader:285:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:30)
    at async link (node:internal/modules/esm/module_job:76:21)
Child exited with error exit status 1INIT_REPORT Init Duration: 233.16 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
SyntaxError: Identifier 'url' has already been declared
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:167:18)
    at callTranslator (node:internal/modules/esm/loader:285:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:30)
    at async link (node:internal/modules/esm/module_job:76:21)
INIT_REPORT Init Duration: 440.83 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
Error: Runtime exited without providing a reason
Runtime.ExitError
```

**Comment by magne4000** [comment]
Oh, I think I know what happens here, let me check

**Comment by CryptoGraffe** [comment]
Took the discussion over here @magne4000 https://github.com/magne4000/vite-plugin-vercel/issues/62
