### ISSUE TITLE
v5 failing with duplicate path/url errors

### ISSUE THREAD

**Issue by CryptoGraffe** [magne4000/vite-plugin-vercel#62]
```
SyntaxError: Identifier 'url' has already been declared
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:167:18)
    at callTranslator (node:internal/modules/esm/loader:285:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:30)
    at async link (node:internal/modules/esm/module_job:76:21)
Child exited with error exit status 1INIT_REPORT Init Duration: 233.16 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
SyntaxError: Identifier 'url' has already been declared
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:167:18)
    at callTranslator (node:internal/modules/esm/loader:285:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:30)
    at async link (node:internal/modules/esm/module_job:76:21)
INIT_REPORT Init Duration: 440.83 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
Error: Runtime exited without providing a reason
Runtime.ExitError
```

```
SyntaxError: Identifier 'path' has already been declared
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:167:18)
    at callTranslator (node:internal/modules/esm/loader:285:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:30)
    at async link (node:internal/modules/esm/module_job:76:21)
INIT_REPORT Init Duration: 1174.47 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
Error: Runtime exited without providing a reason
Runtime.ExitErro
```

**Comment by CryptoGraffe** [comment]
@magne4000 5.0.3 seems to work so far, doing more extensive testing.

**Comment by CryptoGraffe** [comment]
@magne4000 this somehow stopped working .. in that we can no longer build:

```
❯ pnpm build

> coordinape-app@0.2.0 build /Users/nico/dev/coordinape
> tsc && vite build -v

failed to load config from /Users/nico/dev/coordinape/vite.config.ts
error during build:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'workspace-root' imported from /Users/nico/dev/coordinape/node_modules/.pnpm/vite-plugin-vercel@5.0.3_vite@5.0.11/node_modules/vite-plugin-vercel/dist/index.js
    at packageResolve (node:internal/modules/esm/resolve:853:9)
    at moduleResolve (node:internal/modules/esm/resolve:910:20)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by CryptoGraffe** [comment]
Really strange but explicitly depending on workspace-root fixes this. Your package.json looks fine, I have no idea what's going on.

**Comment by CryptoGraffe** [comment]
This workaround is working for me now, but cypress is still hosed:


```
Oops...we found an error preparing this test file:

  > cypress/support/e2e.ts

The error was:

Error: ENOENT: no such file or directory, open '/home/circleci/project/.vercel/output/functions/api/time.func/.vc-config.json'
    at Object.wrapChildPromise (/home/circleci/.cache/Cypress/13.6.2/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:58:23)
    at Object.wrap (/home/circleci/.cache/Cypress/13.6.2/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/preprocessor.js:47:8)
    at RunPlugins.execute (/home/circleci/.cache/Cypress/13.6.2/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:157:29)
    at EventEmitter.<anonymous> (/home/circleci/.cache/Cypress/13.6.2/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:56:12)
    at EventEmitter.emit (node:events:518:28)
    at process.<anonymous> (/home/circleci/.cache/Cypress/13.6.2/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
From previous event:
    at Object.getFile (<embedded>:4474:14887)
    at Object.handle (<embedded>:4474:15891)
    at <embedded>:4513:64793
    at i.handle_request (<embedded>:2701:1038)
    at d (<embedded>:2716:1285)
    at p.dispatch (<embedded>:2716:1307)
    at i.handle_request (<embedded>:2701:1038)
    at <embedded>:2724:3353
    at y.process_params (<embedded>:2724:4284)
    at h (<embedded>:2724:3296)
    at y.handle (<embedded>:2724:4188)
    at o (<embedded>:2724:1048)
    at i.handle_request (<embedded>:2701:1038)
    at <embedded>:2724:3774
    at <embedded>:2724:3796
    at y.process_params (<embedded>:2724:4284)
    at h (<embedded>:2724:3296)
    at i.handle_request (<embedded>:2701:1030)
    at <embedded>:2724:3774
    at <embedded>:2724:3796
    at y.process_params (<embedded>:2724:4284)
    at h (<embedded>:2724:3296)
    at <embedded>:2525:2495
    at i.handle_request (<embedded>:2701:1038)
    at <embedded>:2724:3774
    at <embedded>:2724:3796
    at y.process_params (<embedded>:2724:4284)
    at h (<embedded>:2724:3296)
    at <embedded>:2545:1024
    at i.handle_request (<embedded>:2701:1038)
    at <embedded>:2724:3774
    at <embedded>:2724:3796
    at y.process_params (<embedded>:2724:4284)
    at h (<embedded>:2724:3296)
    at <embedded>:4526:11174
    at i.handle_request (<embedded>:2701:1038)
    at <embedded>:2724:3774
    at <embedded>:2724:3796
    at y.process_params (<embedded>:2724:4284)
    at h (<embedded>:2724:3296)
    at <embedded>:4526:10849
    at i.handle_request (<embedded>:2701:1038)
    at <embedded>:2724:3774
    at <embedded>:2724:3796
    at y.process_params (<embedded>:2724:4284)
    at h (<embedded>:2724:3296)
    at <embedded>:2732:330
    at i.handle_request (<embedded>:2701:1038)
    at <embedded>:2724:3774
    at <embedded>:2724:3796
    at y.process_params (<embedded>:2724:4284)
    at h (<embedded>:2724:3296)
    at <embedded>:2740:544
    at i.handle_request (<embedded>:2701:1038)
    at <embedded>:2724:3774
    at <embedded>:2724:3796
    at y.process_params (<embedded>:2724:4284)
    at h (<embedded>:2724:3296)
    at y.handle (<embedded>:2724:4188)
    at T.handle (<embedded>:2796:3475)
    at Server.e (<embedded>:2827:742)
    at Server.<anonymous> (<embedded>:4423:71058)
    at <embedded>:4526:13978
    at Array.map (<anonymous>)
    at Q._callRequestListeners (<embedded>:4526:13968)
    at Server.<anonymous> (<embedded>:4526:14118)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:1072:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
```

**Comment by magne4000** [comment]
@CryptoGraffe I replaced `workspace-root` by the more popular `@manypkg/find-root` in `v5.0.4`.
Let's hope this "fixes" the issue (I have no idea either why you needed to manually add `workspace-root`)

**Comment by 4350pChris** [comment]
I've had the same issue - `v5.0.4` does indeed fix it.

**Comment by magne4000** [comment]
:+1: clsing the issue then
