### ISSUE TITLE
How to load relative files in node serverless function?

### ISSUE THREAD

**Issue by CryptoGraffe** [magne4000/vite-plugin-vercel#66]
I'd like to bundle some TTF files with my node serverless function and then load them at runtime as custom fonts for vercel/og. Any suggestion on how to accomplish this?

**Comment by magne4000** [comment]
You would have to do something like this:

```ts
const font = readFileSync(join(__dirname, './Roboto-Regular.ttf'));
```

See https://github.com/magne4000/vite-plugin-vercel/pull/67/files#diff-5fe116b362770fc748c624289571e96a596d6e5022971526741a5ec320fcba58

Be sure to update to `v5.0.5` to avoid some warning.

**Comment by CryptoGraffe** [comment]
@magne4000 awesome thanks! How does it know to bundle the ttf files into the function?

**Comment by magne4000** [comment]
It uses [@vercel/nft](https://www.npmjs.com/package/@vercel/nft) for that, so anything with a combination of `__dirname` and `readFile` that can be statically analyzed should work.
It _should_ also work with `import.meta.url`, but for now it doesn't, so I recommened to stick with `__dirname` for now (which is polyfilled during build)

**Comment by CryptoGraffe** [comment]
I'm having a problem where it seems to be trying to read the ttf file as code, i'm using 5.0.5:

```
⚡ Done in 15ms
Warning: failed to read exports of '/Users/user/dev/coordinape/_api/frames/Denim-Regular.ttf' SyntaxError: Unexpected character ''. (1:0)
    at constructor (/Users/user/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:356:19)
    at V8IntrinsicMixin.raise (/Users/user/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:3223:19)
    at V8IntrinsicMixin.getTokenFromCode (/Users/user/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:2885:16)
    at V8IntrinsicMixin.getTokenFromCode (/Users/user/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:6965:11)
    at V8IntrinsicMixin.getTokenFromCode (/Users/user/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:9847:11)
    at V8IntrinsicMixin.nextToken (/Users/user/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:2347:10)
    at V8IntrinsicMixin.parse (/Users/user/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:14374:10)
    at V8IntrinsicMixin.parse (/Users/user/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:9982:18)
    at Module.parse (/Users/user/dev/coordinape/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:14417:38)
    at Object.parse (file:///Users/user/dev/coordinape/node_modules/.pnpm/magicast@0.3.3/node_modules/magicast/dist/index.mjs:7819:26)
    at parse (file:///Users/user/dev/coordinape/node_modules/.pnpm/magicast@0.3.3/node_modules/magicast/dist/index.mjs:4590:30)
    at parseModule (file:///Users/user/dev/coordinape/node_modules/.pnpm/magicast@0.3.3/node_modules/magicast/dist/index.mjs:8770:16)
    at loadFile (file:///Users/user/dev/coordinape/node_modules/.pnpm/magicast@0.3.3/node_modules/magicast/dist/index.mjs:8807:10)
    at async removeDefaultExport (file:///Users/user/dev/coordinape/node_modules/.pnpm/vite-plugin-vercel@5.0.5_vite@5.0.11/node_modules/vite-plugin-vercel/dist/index.js:486:15)
    at async extractExports (file:///Users/user/dev/coordinape/node_modules/.pnpm/vite-plugin-vercel@5.0.5_vite@5.0.11/node_modules/vite-plugin-vercel/dist/index.js:496:22)
    at async buildEndpoints (file:///Users/user/dev/coordinape/node_modules/.pnpm/vite-plugin-vercel@5.0.5_vite@5.0.11/node_modules/vite-plugin-vercel/dist/index.js:526:23)
    at async Object.handler (file:///Users/user/dev/coordinape/node_modules/.pnpm/vite-plugin-vercel@5.0.5_vite@5.0.11/node_modules/vite-plugin-vercel/dist/index.js:744:44)
    at async PluginDriver.hookParallel (file:///Users/user/dev/coordinape/node_modules/.pnpm/rollup@4.9.5/node_modules/rollup/dist/es/shared/node-entry.js:18592:17)
    at async file:///Users/user/dev/coordinape/node_modules/.pnpm/rollup@4.9.5/node_modules/rollup/dist/es/shared/node-entry.js:19590:13
    at async catchUnfinishedHookActions (file:///Users/user/dev/coordinape/node_modules/.pnpm/rollup@4.9.5/node_modules/rollup/dist/es/shared/node-entry.js:19014:16)
    at async build (file:///Users/user/dev/coordinape/node_modules/.pnpm/vite@5.0.11_@types+node@20.11.30/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:67178:22)
    at async CAC.<anonymous> (file:///Users/user/dev/coordinape/node_modules/.pnpm/vite@5.0.11_@types+node@20.11.30/node_modules/vite/dist/node/cli.js:845:9) {
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'InvalidOrUnexpectedToken',
  loc: Position { line: 1, column: 0, index: 0 },
  pos: 0
}
✘ [ERROR] No loader is configured for ".ttf" files: _api/frames/Denim-Regular.ttf

1 error
[vite-plugin-vercel] Build failed with 1 error:
error: No loader is configured for ".ttf" files: _api/frames/Denim-Regular.ttf
✓ built in 12.27s
error during build:
Error: Build failed with 1 error:
error: No loader is configured for ".ttf" files: _api/frames/Denim-Regular.ttf
    at failureErrorWithLog (/Users/user/dev/coordinape/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1651:15)
    at /Users/user/dev/coordinape/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1059:25
    at runOnEndCallbacks (/Users/user/dev/coordinape/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1486:45)
    at buildResponseToResult (/Users/user/dev/coordinape/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1057:7)
    at /Users/user/dev/coordinape/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1086:16
    at responseCallbacks.<computed> (/Users/user/dev/coordinape/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:704:9)
    at handleIncomingPacket (/Users/user/dev/coordinape/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:764:9)
    at Socket.readFromStdout (/Users/user/dev/coordinape/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:680:7)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
 ELIFECYCLE  Command failed with exit code 1.```

**Comment by CryptoGraffe** [comment]
I tried to workaround this by changing the font files to _filename.ttf which lets the build proceed, but my function dir doesn't end up with the ttf files:

```
api/frames/router.func on  font_files [$] via  v20.11.0
❯ ll
total 60760
-rw-r--r--@  1 user  staff  29602525 Apr  3 11:59 index.mjs
-rw-r--r--@  1 user  staff     27748 Apr  3 11:59 noto-sans-v27-latin-regular.ttf
-rw-r--r--@  1 user  staff     88658 Apr  3 11:59 yoga.wasm
-rw-r--r--@  1 user  staff   1378357 Apr  3 11:59 resvg.wasm
drwxr-xr-x@  7 user  staff       224 Apr  3 11:59 .
-rw-r--r--@  1 user  staff       111 Apr  3 11:59 .vc-config.json
drwxr-xr-x@ 15 user  staff       480 Apr  3 11:59 ..
```

Code is like this: 

```
const createFont = (name: string, filename: string) => {
  // TODO: fix font loading in vercel, url fetching is very slow
  let fontData: ArrayBuffer;
  if (!IS_LOCAL_ENV) {
    fontData = readFileSync(join(__dirname, `${filename}`));
  } else {
    const currentFilename = fileURLToPath(import.meta.url);
    const currentDirname = dirname(currentFilename);
    fontData = readFileSync(join(currentDirname, `./${filename}`));
  }

  return {
    name: name,
    data: fontData,
  };
};

export const loadFonts = (): FontOptions[] => {
  const startTime = Date.now();
  const fonts = [
    {
      ...createFont('Denim', '_Denim-Regular.ttf'),
      weight: 400,
      style: 'normal',
    },
    {
      ...createFont('Denim', '_Denim-RegularItalic.ttf'),
      weight: 400,
      style: 'italic',
    },
    {
      ...createFont('Denim', '_Denim-SemiBold.ttf'),
      weight: 600,
      style: 'normal',
    },
    {
      ...createFont('Denim', '_Denim-SemiBoldItalic.ttf'),
      weight: 600,
      style: 'italic',
    },
  ];
  const endTime = Date.now();
  // eslint-disable-next-line no-console
  console.log('Font load time:', endTime - startTime, 'ms');
  return fonts as FontOptions[];
};
```

**Comment by CryptoGraffe** [comment]
Ok I got it working. No fonts in the function dir. This function was key for getting file tracing to find the files:

```
// this function is critical to triggering the node file tracing file bundling
// if this is removed/changed significantly, you need to run pnpm build and look in
// .vercel/output/functions/router.func to make sure ttfs are still there
const getPath = (name: string) =>
  join(process.cwd(), 'public', 'fonts', `${name}.ttf`);

const createFont = (name: string, file: string) => {
  let fontData: ArrayBuffer;
  if (IS_LOCAL_ENV) {
    fontData = readFileSync(getPath(file));
  } else {
    fontData = readFileSync(join(__dirname, `./${file}.ttf`));
  }

  return {
    name: name,
    data: fontData,
  };
};
```

**Comment by magne4000** [comment]
Good to know. I assume that `@vercel/nft` is trying its best, but it cannot handle patterns that are too complex.
